import type {
  Project,
  Drawing,
  CoordinationItem,
  Permit,
  Partner,
} from "@/types";

// 개발용 임시 데이터. 추후 Supabase 연동 시 lib/data.ts 의 fetch 함수로 대체됩니다.

export const projects: Project[] = [
  {
    id: "P-2406",
    name: "판교 도시형 생활주택",
    client: "(주)한울개발",
    phase: "실시설계",
    status: "진행중",
    progress: 72,
    manager: "김세움",
    dueDate: "2026-08-30",
    updatedAt: "2026-06-18",
  },
  {
    id: "P-2412",
    name: "세종 업무시설 리모델링",
    client: "세종도시공사",
    phase: "인허가",
    status: "진행중",
    progress: 88,
    manager: "이도면",
    dueDate: "2026-07-15",
    updatedAt: "2026-06-19",
  },
  {
    id: "P-2503",
    name: "양양 근린생활시설 신축",
    client: "강원리조트",
    phase: "기본설계",
    status: "진행중",
    progress: 41,
    manager: "박설계",
    dueDate: "2026-10-10",
    updatedAt: "2026-06-17",
  },
  {
    id: "P-2418",
    name: "용인 단독주택 단지",
    client: "개인 건축주",
    phase: "계획설계",
    status: "보류",
    progress: 18,
    manager: "김세움",
    dueDate: "2026-09-01",
    updatedAt: "2026-05-30",
  },
  {
    id: "P-2390",
    name: "인천 물류센터",
    client: "(주)코어로지스",
    phase: "준공",
    status: "완료",
    progress: 100,
    manager: "이도면",
    dueDate: "2026-04-20",
    updatedAt: "2026-04-22",
  },
];

export const drawings: Drawing[] = [
  {
    id: "D-1001",
    projectId: "P-2406",
    name: "지하1층_평면도",
    type: "건축",
    version: "Rev.03",
    format: "dwg",
    size: 4_820_000,
    uploadedBy: "김세움",
    uploadedAt: "2026-06-18",
  },
  {
    id: "D-1002",
    projectId: "P-2406",
    name: "기준층_구조평면도",
    type: "구조",
    version: "Rev.02",
    format: "pdf",
    size: 2_140_000,
    uploadedBy: "외주_정구조",
    uploadedAt: "2026-06-16",
  },
  {
    id: "D-1003",
    projectId: "P-2412",
    name: "전체_3D매스",
    type: "건축",
    version: "Rev.01",
    format: "ifc",
    size: 18_500_000,
    uploadedBy: "박설계",
    uploadedAt: "2026-06-19",
  },
  {
    id: "D-1004",
    projectId: "P-2503",
    name: "설비_덕트경로",
    type: "설비",
    version: "Rev.01",
    format: "rvt",
    size: 33_200_000,
    uploadedBy: "외주_한설비",
    uploadedAt: "2026-06-15",
  },
];

export const coordinationItems: CoordinationItem[] = [
  {
    id: "C-501",
    projectId: "P-2406",
    title: "보 춤과 덕트 간섭 검토",
    discipline: "설비",
    status: "협의중",
    assignee: "이도면",
    dueDate: "2026-06-25",
  },
  {
    id: "C-502",
    projectId: "P-2406",
    title: "코어 전기실 면적 조정",
    discipline: "전기",
    status: "수정요청",
    assignee: "박설계",
    dueDate: "2026-06-23",
  },
  {
    id: "C-503",
    projectId: "P-2503",
    title: "조경 데크 레벨 협의",
    discipline: "조경",
    status: "검토대기",
    assignee: "김세움",
    dueDate: "2026-06-30",
  },
];

export const permits: Permit[] = [
  {
    id: "PM-301",
    projectId: "P-2412",
    name: "건축허가 (변경)",
    authority: "세종특별자치시청",
    status: "보완",
    submittedAt: "2026-05-28",
    expectedAt: "2026-07-10",
  },
  {
    id: "PM-302",
    projectId: "P-2406",
    name: "굴토 심의",
    authority: "성남시청",
    status: "접수",
    submittedAt: "2026-06-10",
    expectedAt: "2026-07-05",
  },
  {
    id: "PM-303",
    projectId: "P-2503",
    name: "사전 경관 협의",
    authority: "양양군청",
    status: "준비",
    submittedAt: null,
    expectedAt: "2026-08-01",
  },
];

export const partners: Partner[] = [
  {
    id: "PT-01",
    name: "정구조 엔지니어링",
    type: "구조설계",
    contactPerson: "정한길 소장",
    email: "jung@struct.co.kr",
    phone: "010-1234-5678",
    activeProjects: 2,
  },
  {
    id: "PT-02",
    name: "한설비 기술단",
    type: "설비설계",
    contactPerson: "한미래 부장",
    email: "han@mep.co.kr",
    phone: "010-2345-6789",
    activeProjects: 1,
  },
  {
    id: "PT-03",
    name: "백두 건축사사무소",
    type: "건축설계사",
    contactPerson: "백두산 건축사",
    email: "baek@baekdu.kr",
    phone: "010-3456-7890",
    activeProjects: 3,
  },
  {
    id: "PT-04",
    name: "신속 인허가행정",
    type: "인허가대행",
    contactPerson: "신속해 대표",
    email: "fast@permit.kr",
    phone: "010-4567-8901",
    activeProjects: 2,
  },
];
